config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :courses, :only => [:index, :show]
  resources :lessons, :only => [:show]
  namespace :instructor do
  resources :sections, :only => [] do 
    resources :lessons, :only => [:new, :create] 
  end
    resources :courses, :only => [:new, :create, :show] do
      resources :sections, :only => [:new, :create]
    end
  end
end 

app/models/course.rb
class Course < ActiveRecord::Base
    belongs_to :user
    has_many :sections

  validates :title, :presence => true
  validates :description, :presence => true
  validates :cost, :presence => true, :numericality => {:greater_than_or_equal_to => 0}
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
    belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
   before_action :authenticate_user!
   before_action :require_authorized_for_current_course, :only => [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
   
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render :text => "Unauthorized", :status => :unauthorized
    end
  end
  
  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render :text => 'Unauthorized', :status => :unauthorized
    end
  end
  
  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle)
  end

end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course

  def new
    @section = Section.new
  end

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render :text => "Unauthorized", :status => :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title)
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
  end

    private
    helper_method :current_lesson 
      def current_lesson @current_lesson ||= Lesson.find(params[:id]) 
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
 
 <br />
 <div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Learn something today!</h1>
  <hr />
  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <br />
    <div class="col-sm-8 col-xs-12">
      <p><%= course.description %></p>
    </div>
    <br class="clear" />
    <div class="col-sm-4 col-xs-12 text-center">
      <%= link_to 'More Details...', course_path(course), :class => 'btn btn-primary btn-large' %>
    </div>
      <br class="clear" />
  <% end %>

</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= @course.title %></h1>
    <br />
   <div class="col-sm-4 col-xs-12 text-center">
    <span class="label label-default">
      <%= number_to_currency @course.cost %>
    </span>

      <% if current_user && current_user == @course.user %>
      <br />
      <br />
      <%= link_to 'Administer', instructor_course_path(@course), :class => 'btn btn-danger btn-large' %>
    <% end %>
  </div>

  <div class="col-sm-8 col-xs-12">
    <%= @course.description %>
  </div>

  <div class="col-xs-12">
    <% @course.sections.each do |section| %> 
      <div class="section"> 
        <%= section.title %> 
        <% section.lessons.each do |lesson| %>
          <div class="lesson">
            <%= link_to lesson_path(lesson) do %>
              <b><%= lesson.title %></b>
              -
              <%= lesson.subtitle %>
            <% end %>
          </div>
        <% end %>
      </div> 
      <% end %>
  </div>

</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, :url => instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit "Create", :class => 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
   <h1 class="text-center"><%= current_course.title %></h1>
  <br />
     <%= link_to 'Preview As Student...', course_path(current_course), :class => 'btn btn-warning pull-right' %>
    <br class="clr" />
    <div class="text-center">
     <%= link_to 'Add a new section...', new_instructor_course_section_path(current_course), :class => 'btn btn-primary btn-lg' %>
  </div>
  <ul>
    <% current_course.sections.each do |section| %>
      <li>
        <%= section.title %>
        <%= link_to 'New Lesson', new_instructor_section_lesson_path(section), :class => 'pull-right btn btn-primary btn-xs' %>
  <ul> <% section.lessons.each do |lesson| %> 
    <li> 
      <b><%= lesson.title %></b> - 
          <%= lesson.subtitle %> 
    </li> 
    <% end %> 
  </ul> 
      <br class="clr" /> 
    </li> 
    <% end %> 
  </ul>
</div>

app/views/instructor/lessons/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new lesson</h1>
     <%= simple_form_for @lesson, :url => instructor_section_lessons_path(current_section) do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
        <br />
    <%= f.submit "Add the lesson" %>
        <br />
        <br />
  <% end %>
</div>

app/views/instructor/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new lesson</h1>
</div>

app/views/instructor/sections/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new section</h1>
    <%= simple_form_for @section, :url => instructor_course_sections_path(current_course) do |f| %>
    <%= f.input :title %>
    <br />
    <%= f.submit "Add a section", :class => 'btn btn-primary' %>
    <br />
    <br />
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flixter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrap">
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="#">Flixter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'See All Courses', courses_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
      <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %> 
<p class="alert alert-info"><%= notice %></p> 
<% end %> 
<% if alert.present? %> 
<p class="alert alert-danger"><%= alert %></p> 
<% end %>

<%= yield %>

</div><!-- /wrap -->

<br class="clear" />

  <div id="footer">
    <div class="container">
      <b>Teachers</b>
      <br />
      <%= link_to 'Teach a Course', new_instructor_course_path %>
    </div>
  </div>
</body>
</html>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= current_lesson.title %></h1>
  <p>
    <%= current_lesson.subtitle %>
  </p>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-xs-10 col-xs-offset-1 text-center">
    <div class="frosty">
      <h1>Learn Magic from the Pros</h1>
      <h2>I'm an illusionist, Alan.</h2>
       <br />
        <%= link_to 'Learn More', courses_path, :class => 'btn btn-success' %>
      <br /><br />
    </div><!-- /frosty -->
</div> <!-- /hero -->

<div class="clear" /></div>

<br /><br /><br /><br /><br /><br /><br /><br />


<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="col-sm-4">
    <h3>Feature 1</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 2</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 3</h3>
  </div>
</div><!-- /features -->